spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.xbtdbldewlpsbtmlprqj
spring.datasource.password=XXrt2plY0PFUOhDQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false

spring.secret=minha-chave-super-secreta-com-pelo-menos-32-caracteres-123456
spring.expiracao=60
spring.emissor=moto-api
server.port=8081

# === EMAIL ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=firestorm134679@gmail.com
spring.mail.password=COLOQUE_AQUI_SUA_SENHA_DE_16_LETRAS_DO_GOOGLE
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.frontend.url=http://localhost:5173
app.frontend.reset-path=/reset-password

logging.level.com.example.motoprojetofinal=DEBUG